/*
PROCEDURES DAS APOLICES
*/
/*
	id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	idCliente INT,
	idPlano INT,
	idFuncionario INT,
	formaPagamento INT NOT NULL, CHECK (FormaPagamento IN(0,1,2)),
	valorSeguro DECIMAL NOT NULL,
	dataCriacaoApolice DATETIME NOT NULL,
	tempoContratacaoPorMes INT NOT NULL,
*/

CREATE PROCEDURE GetAllApolices
AS
SELECT * FROM APOLICES
GO;

CREATE PROCEDURE PostApolice
@IDCLIENTE INT,
@IDPLANO INT,
@IDFUNCIONARIO INT,
@FORMAPAGAMENTO INT,
@VALORSEGURO DECIMAL,
@DATACRIACAOAPOLICE DATETIME,
@TEMPOCONTRATACAOPORMES INT
AS
INSERT INTO APOLICES(idCliente, idPlano, idFuncionario,formaPagamento,valorSeguro,dataCriacaoApolice,tempoContratacaoPorMes )
VALUES(@IDPLANO, @IDPLANO, @IDFUNCIONARIO, @FORMAPAGAMENTO, @VALORSEGURO, @DATACRIACAOAPOLICE, @TEMPOCONTRATACAOPORMES)
GO;

CREATE PROCEDURE PutApolice
@ID INT,
@FORMAPAGAMENTO INT,
@VALORSEGURO DECIMAL,
@TEMPOCONTRATACAOPORMES INT
AS
UPDATE APOLICES 
SET APOLICES.formaPagamento = @FORMAPAGAMENTO, APOLICES.valorSeguro = @VALORSEGURO, APOLICES.tempoContratacaoPorMes = @TEMPOCONTRATACAOPORMES
WHERE APOLICES.id = @ID
GO;

CREATE PROCEDURE DeleteApolice
@ID INT
AS
DELETE FROM APOLICES
WHERE APOLICES.id = @ID;
GO;