/*
PROCEDURES DOS ASSISTENCIAS
*/

/*
	id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	idPlano INT NOT NULL,
	descricao VARCHAR(50) NOT NULL,
	contato VARCHAR(50) NOT NULL,
*/

CREATE PROCEDURE GetAllAssistencias
AS
SELECT * FROM ASSISTENCIAS
GO;

CREATE PROCEDURE PostAssistencia
@IDPLANO INT,
@DESCRICAO VARCHAR(50),
@CONTATO VARCHAR(50) 
AS
INSERT INTO ASSISTENCIAS(idPlano, descricao, contato)
VALUES(@IDPLANO, @DESCRICAO, @CONTATO)
GO;

CREATE PROCEDURE PutAssistencia
@ID INT,
@DESCRICAO VARCHAR(50),
@CONTATO VARCHAR(50)  
AS
UPDATE ASSISTENCIAS 
SET ASSISTENCIAS.descricao = @DESCRICAO, ASSISTENCIAS.contato = @CONTATO
WHERE ASSISTENCIAS.id = @ID
GO;

CREATE PROCEDURE DeleteAssistencia
@ID INT
AS
DELETE FROM ASSISTENCIAS
WHERE ASSISTENCIAS.id = @ID;
GO;