CREATE PROCEDURE GetAllAutomoveis
AS
SELECT * FROM AUTOMOVEIS
GO;

CREATE PROCEDURE PostAutomovel
@IDCLIENTE INT,
@MODELO VARCHAR(50),
@MARCA VARCHAR(50),
@ANOMODELO VARCHAR(4),
@COR VARCHAR(50),
@PLACA VARCHAR(7),
@RENAVAM VARCHAR(50),
@NUMEROMOTOR VARCHAR(50),
@CRLV VARCHAR(50)
AS
INSERT INTO AUTOMOVEIS(
auto_cli_id, auto_placa, auto_modelo, auto_marca, auto_anoModelo, 
auto_cor, auto_renavam, auto_numeroMotor, auto_crlv, auto_status)
VALUES(@IDCLIENTE, @PLACA ,@MODELO, @MARCA, @ANOMODELO, @COR, @RENAVAM, @NUMEROMOTOR, @CRLV, 2)
GO;

CREATE PROCEDURE PutAutomovel
@ID INT,
@MODELO VARCHAR(50),
@MARCA VARCHAR(50),
@ANOMODELO VARCHAR(4),
@COR VARCHAR(50),
@RENAVAM VARCHAR(50),
@NUMEROMOTOR VARCHAR(50),
@CRLV VARCHAR(50) 
AS
UPDATE AUTOMOVEIS 
SET AUTOMOVEIS.auto_modelo = @MODELO, 
AUTOMOVEIS.auto_marca = @MARCA, 
AUTOMOVEIS.auto_anoModelo = @ANOMODELO, 
AUTOMOVEIS.auto_cor = @COR, 
AUTOMOVEIS.auto_renavam = @RENAVAM, 
AUTOMOVEIS.auto_numeroMotor = @NUMEROMOTOR, 
AUTOMOVEIS.auto_crlv = @CRLV
WHERE AUTOMOVEIS.auto_id = @ID
GO;

CREATE PROCEDURE ChangeStatusAutomovelById 
@ID INT,
@STATUS BIT 
AS 
UPDATE AUTOMOVEIS
SET AUTOMOVEIS.auto_status = @STATUS
WHERE AUTOMOVEIS.auto_id = @ID 
GO;


CREATE PROCEDURE DeleteAutomovel
@ID INT
AS
DELETE FROM AUTOMOVEIS
WHERE AUTOMOVEIS.auto_id = @ID;
GO;