/*
PROCEDURES DOS AUTOMOVEIS
*/

CREATE PROCEDURE GetAllAutomoveis
AS
SELECT * FROM AUTOMOVEIS
GO;

CREATE PROCEDURE PostAutomovel
@IDCLIENTE INT,
@MODELO VARCHAR(50),
@MARCA VARCHAR(50),
@ANOMODELO VARCHAR(4),
@COR VARCHAR(50),
@RENAVAM VARCHAR(50),
@NUMEROMOTOR VARCHAR(50),
@CRLV VARCHAR(50) 
AS
INSERT INTO AUTOMOVEIS(idCliente, modelo, marca, anoModelo, cor, renavam, numeroMotor, crlv)
VALUES(@IDCLIENTE, @MODELO, @MARCA, @ANOMODELO, @COR, @RENAVAM, @NUMEROMOTOR, @CRLV)
GO;

CREATE PROCEDURE PutAutomovel
@ID INT,
@MODELO VARCHAR(50),
@MARCA VARCHAR(50),
@ANOMODELO VARCHAR(4),
@COR VARCHAR(50),
@RENAVAM VARCHAR(50),
@NUMEROMOTOR VARCHAR(50),
@CRLV VARCHAR(50) 
AS
UPDATE AUTOMOVEIS 
SET AUTOMOVEIS.modelo = @MODELO, AUTOMOVEIS.marca = @MARCA, AUTOMOVEIS.anoModelo = @ANOMODELO, AUTOMOVEIS.cor = @COR, AUTOMOVEIS.renavam = @RENAVAM, AUTOMOVEIS.numeroMotor = @NUMEROMOTOR, AUTOMOVEIS.crlv = @CRLV
WHERE AUTOMOVEIS.id = @ID
GO;

CREATE PROCEDURE DeleteAutomovel
@ID INT
AS
DELETE FROM AUTOMOVEIS
WHERE AUTOMOVEIS.id = @ID;
GO;