CREATE PROCEDURE GetAllCoberturas
AS
SELECT * FROM COBERTURAS
GO;

CREATE PROCEDURE PostCobertura
@IDPLANO INT,
@NOME VARCHAR(50),
@DESCRICAO VARCHAR(200),
@INDENIZACAO DECIMAL 
AS
INSERT INTO COBERTURAS(cober_plan_id , cober_descricao, cober_indenizacao, cober_nome)
VALUES(@IDPLANO, @DESCRICAO, @INDENIZACAO, @NOME)
GO;

CREATE PROCEDURE PutCobertura
@ID INT,
@DESCRICAO VARCHAR(200),
@INDENIZACAO DECIMAL 
AS
UPDATE COBERTURAS 
SET COBERTURAS.cober_descricao = @DESCRICAO, 
COBERTURAS.cober_indenizacao = @INDENIZACAO
WHERE COBERTURAS.cober_id = @ID
GO;

CREATE PROCEDURE DeleteCobertura
@ID INT
AS
DELETE FROM COBERTURAS
WHERE COBERTURAS.cober_id = @ID;
GO;