/*
PROCEDURES DOS COBERTURA
*/

CREATE PROCEDURE GetAllCoberturas
AS
SELECT * FROM COBERTURAS
GO;

CREATE PROCEDURE PostCobertura
@IDPLANO INT,
@DESCRICAO VARCHAR(50),
@INDENIZACAO DECIMAL 
AS
INSERT INTO COBERTURAS(idPlano, descricao, indenizacao)
VALUES(@IDPLANO, @DESCRICAO, @INDENIZACAO)
GO;

CREATE PROCEDURE PutCobertura
@ID INT,
@DESCRICAO VARCHAR(50),
@INDENIZACAO DECIMAL 
AS
UPDATE COBERTURAS 
SET COBERTURAS.descricao = @DESCRICAO, COBERTURAS.indenizacao = @INDENIZACAO
WHERE COBERTURAS.id = @ID
GO;

CREATE PROCEDURE DeleteCobertura
@ID INT
AS
DELETE FROM COBERTURAS
WHERE COBERTURAS.id = @ID;
GO;