/*
PROCEDURES DOS FUNCIONARIOS
	GetAllFuncionarios
	GetFuncionarioById
	PostFuncionario
	PutFuncionario
	ChangeFuncionarioStatus
	DeleteFuncionario
*/

CREATE PROCEDURE GetAllFuncionarios
AS
SELECT * FROM FUNCIONARIOS
GO;

CREATE PROCEDURE PostFuncionario
@NOME VARCHAR(50),
@EMAIL VARCHAR(50),
@SENHA VARCHAR(12),
@DATANASCIMENTO VARCHAR(10),
@CPF VARCHAR(11),
@RG VARCHAR(11),
@CTPS VARCHAR(11),
@TELEFONE VARCHAR(11),
@CARGO VARCHAR(50),
@SETOR INT
AS
SELECT PARSE(@DATANASCIMENTO as date USING 'AR-LB')
INSERT INTO FUNCIONARIOS(nome, email, senha, dataNascimento, cpf, rg, ctps, setor,telefone, cargo, isAtivo)
VALUES(@NOME, @EMAIL, @SENHA, @DATANASCIMENTO, @CPF, @RG, @CTPS, @SETOR , @TELEFONE,@CARGO, 'TRUE')
GO;

CREATE PROCEDURE PutFuncionario
@EMAIL VARCHAR(50),
@SENHA VARCHAR(12),
@TELEFONE VARCHAR(11),
@SETOR VARCHAR(20),
@CARGO VARCHAR(50),
@ID INT
AS
UPDATE FUNCIONARIOS 
SET FUNCIONARIOS.email = @EMAIL, FUNCIONARIOS.senha = @SENHA, FUNCIONARIOS.telefone = @TELEFONE, FUNCIONARIOS.cargo = @CARGO, FUNCIONARIOS.setor = @SETOR
WHERE FUNCIONARIOS.id = @ID
GO;

CREATE PROCEDURE ChangeFuncionarioStatus
@STATUS BIT,
@ID INT
AS
UPDATE FUNCIONARIOS 
SET FUNCIONARIOS.isAtivo = @STATUS
WHERE FUNCIONARIOS.id = @ID
GO;

CREATE PROCEDURE DeleteFuncionario
@ID INT
AS
DELETE FROM FUNCIONARIOS 
WHERE FUNCIONARIOS.id = @ID
GO;


EXEC GetAllFuncionarios;
EXEC PostFuncionario @NOME = 'Nicolas Paxãpo', @EMAIL = 'exemplo@gmail.com', @SENHA ='Tsb20Nic@',
					 @DATANASCIMENTO ='17/11/2000', @CPF ='12345678911', @RG='1223478411' , 
					 @CTPS ='1234567', @TELEFONE ='119888888', @CARGO='VENDEDOR', @SETOR = 0;
