/*
PROCEDURES DOS FUNCIONARIOS
	GetAllFuncionarios
	GetFuncionarioById
	PostFuncionario
	PutFuncionario
	ChangeFuncionarioStatus
	DeleteFuncionario
*/

CREATE PROCEDURE GetAllFuncionarios
AS
SELECT * FROM FUNCIONARIOS
GO;

CREATE PROCEDURE PostFuncionario
@NOME VARCHAR(50),
@EMAIL VARCHAR(50),
@DATANASCIMENTO VARCHAR(10),
@DATAADMISSAO VARCHAR(10),
@SEXO INT,
@CPF VARCHAR(11),
@RG VARCHAR(11),
@CEP VARCHAR(8),
@TELEFONE VARCHAR(11),
@CARGO VARCHAR(50)
AS
SELECT PARSE(@DATAADMISSAO as date USING 'AR-LB')
SELECT PARSE(@DATANASCIMENTO as date USING 'AR-LB')
INSERT INTO FUNCIONARIOS(nome, email, senha, sexo, dataNascimento,dataAdmissao, cep,cpf, rg, telefone, cargo, isAtivo)
VALUES(@NOME, @EMAIL, @CPF, @SEXO, @DATANASCIMENTO, @DATAADMISSAO, @CEP, @CPF, @RG, @TELEFONE, @CARGO, 'TRUE')
GO;

CREATE PROCEDURE PutFuncionario
@EMAIL VARCHAR(50),
@SENHA VARCHAR(11),
@TELEFONE VARCHAR(11),
@CARGO VARCHAR(50),
@ID INT
AS
UPDATE FUNCIONARIOS 
SET FUNCIONARIOS.email = @EMAIL, FUNCIONARIOS.senha = @SENHA, FUNCIONARIOS.telefone = @TELEFONE, FUNCIONARIOS.cargo = @CARGO
WHERE FUNCIONARIOS.funcionario_id = @ID
GO;

CREATE PROCEDURE ChangeFuncionarioStatus
@STATUS BIT,
@ID INT
AS
UPDATE FUNCIONARIOS 
SET FUNCIONARIOS.isAtivo = @STATUS
WHERE FUNCIONARIOS.funcionario_id = @ID
GO;

CREATE PROCEDURE DeleteFuncionario
@ID INT
AS
DELETE FROM FUNCIONARIOS 
WHERE FUNCIONARIOS.funcionario_id = @ID
GO;


EXEC GetAllFuncionarios;
EXEC PostFuncionario @NOME = 'Nicolas Paxão', @EMAIL = 'exemplo@gmail.com', @SEXO = 1,
					 @DATANASCIMENTO ='17/11/2000', @DATAADMISSAO = '08/08/2022', @CPF ='12345678911', @CEP = '06449150',
					 @RG='1223478411', @TELEFONE ='119888888', @CARGO='VENDEDOR';
