CREATE PROCEDURE GetAllPlanos
AS
SELECT * FROM PLANOS
GO;

CREATE PROCEDURE PostPlano
@NOMEPLANO VARCHAR(50),
@IDSEGURADORA INT,
@TIPOPLANO INT
AS
INSERT INTO PLANOS(plan_nomePlano, plan_segu_id, plan_tipoPlano, plan_status)
VALUES(@NOMEPLANO, @IDSEGURADORA, @TIPOPLANO, 0)
GO;

CREATE PROCEDURE PutPlano
@ID INT,
@NOMEPLANO VARCHAR(50)
AS
UPDATE PLANOS 
SET PLANOS.plan_nomePlano = @NOMEPLANO
WHERE PLANOS.plan_id = @ID
GO;

CREATE PROCEDURE DeletePlano
@ID INT
AS
DELETE FROM PLANOS
WHERE PLANOS.plan_id = @ID;
GO;