/*
PROCEDURES DOS PLANOS
*/
CREATE PROCEDURE GetAllPlanos
AS
SELECT * FROM PLANOS
GO;

CREATE PROCEDURE PostPlano
@NOMEPLANO VARCHAR(50),
@IDSEGURADORA INT,
@TIPOPLANO INT
AS
INSERT INTO PLANOS(nomePlano, idSeguradora, tipoPlano)
VALUES(@NOMEPLANO, @IDSEGURADORA, @TIPOPLANO)
GO;

CREATE PROCEDURE PutPlano
@ID INT,
@NOMEPLANO VARCHAR(50)
AS
UPDATE PLANOS 
SET PLANOS.nomePlano = @NOMEPLANO
WHERE PLANOS.id = @ID
GO;

CREATE PROCEDURE DeletePlano
@ID INT
AS
DELETE FROM PLANOS
WHERE PLANOS.id = @ID;
GO;