CREATE PROCEDURE GetAllPlanos
AS
SELECT * FROM PLANOS
GO;

CREATE PROCEDURE PostPlano
@NOMEPLANO VARCHAR(50),
@IDSEGURADORA INT,
@VALOR DECIMAL,
@TIPOPLANO INT
AS
BEGIN 
	IF NOT EXISTS (SELECT * FROM PLANOS WHERE PLANOS.plan_nomePlano = @NOMEPLANO)
	BEGIN
		INSERT INTO PLANOS(plan_nomePlano, plan_valor,plan_segu_id, plan_tipoPlano, plan_status)
		VALUES(@NOMEPLANO, @VALOR,@IDSEGURADORA, @TIPOPLANO, 0)
	END
END
GO;

CREATE PROCEDURE PutPlano
@ID INT,
@VALOR DECIMAL,
@NOMEPLANO VARCHAR(50)
AS
UPDATE PLANOS 
SET PLANOS.plan_nomePlano = @NOMEPLANO,
	PLANOS.plan_valor = @VALOR
WHERE PLANOS.plan_id = @ID
GO;

CREATE PROCEDURE DeletePlano
@ID INT
AS
DELETE FROM PLANOS
WHERE PLANOS.plan_id = @ID;
GO;
