/*
PROCEDURES DOS SEGURADORAS
*/

CREATE PROCEDURE GetAllSeguradoras
AS
SELECT * FROM SEGURADORAS
GO;

CREATE PROCEDURE PostSeguradora
@RAZAOSOCIAL VARCHAR(50),
@CNPJ VARCHAR(50),
@CONTRATOSOCIAL VARCHAR(50),
@EMAIL VARCHAR(50),
@TELEFONE VARCHAR(11) 
AS
INSERT INTO SEGURADORAS(razaoSocial, cnpj, contratoSocial, email, telefone)
VALUES(@RAZAOSOCIAL, @CNPJ, @CONTRATOSOCIAL, @EMAIL, @TELEFONE)
GO;

CREATE PROCEDURE PutSeguradora
@ID INT,
@EMAIL VARCHAR(50),
@TELEFONE VARCHAR(11) 
AS
UPDATE SEGURADORAS 
SET SEGURADORAS.email = @EMAIL, SEGURADORAS.telefone = @TELEFONE
WHERE SEGURADORAS.id = @ID
GO;

CREATE PROCEDURE DeleteSeguradora
@ID INT
AS
DELETE FROM SEGURADORAS
WHERE SEGURADORAS.id = @ID;
GO;