USE TSBSEGUROS

USE TSBSEGUROS

/*
	Tabelas:
		Funcionario
		Cliente
		Automovel
		Seguradora
		Cobertura
		Assistencia
		Plano
		Apolice

	Tabelas de Relacionamento:
		Plano_Assistencia
		Plano_Cobertura
*/

/* --- TABELAS PRINCIPAIS --- */
CREATE TABLE FUNCIONARIO(
	Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	Nome VARCHAR(50) NOT NULL,
	Email VARCHAR(50),
	Senha VARCHAR(50),
	Data_Nascimento DATETIME NOT NULL,
	Cpf VARCHAR(11) NOT NULL,
	Rg VARCHAR(11) NOT NULL,
	Ctps VARCHAR(20) NOT NULL,
	Telefone VARCHAR(20) NOT NULL,
	Cargo VARCHAR(50) NULL,
	IsAtivo BIT NOT NULL,
);

CREATE TABLE CLIENTE (
    Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	Email VARCHAR(50),
	Senha VARCHAR(50),
    Nome VARCHAR(50),
	Razao_Social VARCHAR(50),
	CNPJ VARCHAR(50),
	CPF VARCHAR(50),
	CNH VARCHAR(50),
	Data_Nascimento DATETIME,
	Data_Criacao DATETIME,
	TipoCliente VARCHAR(20) NOT NULL, CHECK (TipoCliente IN('PJ', 'PF'))
);

CREATE TABLE AUTOMOVEL (
    Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	Id_Cliente INT NOT NULL,
    Modelo VARCHAR(50)NOT NULL,
	Marca VARCHAR(50)NOT NULL,
	Ano_Modelo VARCHAR(4) NOT NULL,
	Cor VARCHAR(50)NOT NULL,
	Renavam VARCHAR(50)NOT NULL,
	Numero_Motor VARCHAR(50)NOT NULL,
	CRLV VARCHAR(50)NOT NULL,
	FOREIGN KEY (Id_Cliente) REFERENCES CLIENTE(Id) ON DELETE CASCADE,
);

SELECT cliente.Id,cliente.Nome,automovel.Id,automovel.Modelo, automovel.Marca, automovel.Ano_Modelo FROM AUTOMOVEL automovel
JOIN CLIENTE cliente
ON cliente.Id = automovel.Id_Cliente
WHERE cliente.Id = 1


INSERT INTO AUTOMOVEL VALUES(1,'Golf GTI', 'Volkswagem', '2012', 'Preto','32215115545','21232524262728','1515114141')

CREATE TABLE SEGURADORA(
	Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	Razao_Social VARCHAR(50) NOT NULL,
	CNPJ VARCHAR(50) NOT NULL,
	Contrato_Social VARCHAR(50) NOT NULL,
	Email VARCHAR(50) NOT NULL,
	Telefone VARCHAR(11) NOT NULL,
);

CREATE TABLE ASSISTENCIA(
	Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	Descricao VARCHAR(50) NOT NULL,
	Contato VARCHAR(50) NOT NULL,
);

CREATE TABLE COBERTURA(
	Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	Descricao VARCHAR(50) NOT NULL,
	Indenizacao VARCHAR(50) NOT NULL,
);

CREATE TABLE PLANO(
	Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	Nome_Plano VARCHAR(50),
	Id_Seguradora INT NOT NULL,
	TipoPlano VARCHAR(20) NOT NULL, CHECK (TipoPlano IN('PADRAO', 'PREMIUM', 'SUPER')),
	FOREIGN KEY (Id_Seguradora) REFERENCES SEGURADORA(ID) ON DELETE CASCADE,
);

CREATE TABLE APOLICE(
	Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	IdCliente INT NOT NULL,
	IdPlano INT NOT NULL,
	IdFuncionario INT NOT NULL,
	FormaPagamento VARCHAR(20) NOT NULL, CHECK (FormaPagamento IN('CARTAO_CREDITO', 'PIX', 'BOLETO')),
	Valor_Seguro DECIMAL NOT NULL,
	Data_Criacao_Apolice DATETIME NOT NULL,
	FOREIGN KEY (IdCliente) REFERENCES CLIENTE(ID) ON DELETE CASCADE,
	FOREIGN KEY (IdPlano) REFERENCES PLANO(ID) ON DELETE CASCADE,
	FOREIGN KEY (IdFuncionario) REFERENCES FUNCIONARIO(ID) ON DELETE CASCADE,
);

CREATE TABLE PLANO_ASSISTENCIA(
	Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    Id_Plano INT  NOT NULL,
    Id_Assistencia INT  NOT NULL,
	FOREIGN KEY (Id_Plano) REFERENCES PLANO(Id) ON DELETE CASCADE,
	FOREIGN KEY (Id_Assistencia) REFERENCES ASSISTENCIA(Id) ON DELETE CASCADE,
);

CREATE TABLE PLANO_COBERTURA(
	Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    Id_Plano INT  NOT NULL,
    Id_Cobertura INT  NOT NULL,
	FOREIGN KEY (Id_Plano) REFERENCES PLANO(Id) ON DELETE CASCADE,
	FOREIGN KEY (Id_Cobertura) REFERENCES COBERTURA(Id) ON DELETE CASCADE
);

/* --- FUNÇÕES --- */



SELECT * FROM FUNCIONARIO
SELECT * FROM CLIENTE
SELECT * FROM AUTOMOVEL
SELECT * FROM COBERTURA
SELECT * FROM ASSISTENCIA
SELECT * FROM SEGURADORA
SELECT * FROM PLANO
SELECT * FROM APOLICE
SELECT * FROM CLIENTE_AUTOMOVEL
SELECT * FROM PLANO_ASSISTENCIA
SELECT * FROM PLANO_COBERTURA




































 

/*
SELECT * FROM CLIENTE
SELECT * FROM AUTOMOVEL
SELECT * FROM CLIENTE_AUTOMOVEL

INSERT INTO Cliente VALUES('Nicolas');
INSERT INTO Cliente VALUES('Antonio');

INSERT INTO Automovel VALUES('Golf', 1);
INSERT INTO Automovel VALUES('Azira', 3);
INSERT INTO Automovel VALUES('Strada',1);
INSERT INTO Automovel VALUES('Marea', 3);
INSERT INTO Automovel VALUES('Astra', 1);


CREATE TABLE CLIENTE_AUTOMOVEL (
	Id INT IDENTITY(1,1) NOT NULL,
    Id_Cliente INT,
    Id_Automovel INT,
	FOREIGN KEY (IdAutomovel) REFERENCES AUTOMOVEL(Id) ON DELETE CASCADE,
	FOREIGN KEY (IdCliente) REFERENCES CLIENTE(Id) ON DELETE CASCADE,
);


SELECT c.ClienteId, c.Nome, ca.IdCliente, ca.IdAutomovel, a.Nome FROM Cliente c
JOIN Cliente_Automovel ca
ON c.ClienteId = ca.IdCliente
JOIN Automovel a
ON ca.IdAutomovel = a.Automoveld

DELETE oba FROM Automovel oba
WHERE oba.Automoveld = 3

DELETE a FROM Cliente a
WHERE a.ClienteId = 2


DROP TABLE Cliente
DROP TABLE Automovel
DROP TABLE Cliente_Automovel
*/